const db = {
    'water': { name: 'Вода', icon: '💧', tier: 1, desc: 'Простейшая жидкость, основа биологической жизни.' },
    'fire':  { name: 'Огонь', icon: '🔥', tier: 1, desc: 'Активный плазменный процесс, источник тепловой энергии.' },
    'earth': { name: 'Земля', icon: '🌍', tier: 1, desc: 'Твердое основание, несущее в себе минералы.' },
    'air':   { name: 'Воздух', icon: '💨', tier: 1, desc: 'Газовая оболочка, обеспечивающая атмосферное давление.' },
    'time': {name: 'Время', icon: '⏳', tier: 1, desc: 'Просто время...'},

    'steam':  { name: 'Пар', icon: '☁️', tier: 2, desc: 'Газообразное состояние воды под тепловым воздействием.' },
    'lava':   { name: 'Лава', icon: '🌋', tier: 2, desc: 'Расплавленная порода, вырывающаяся из глубин коры.' },
    'energy': { name: 'Энергия', icon: '⚡', tier: 2, desc: 'Кванты силы, запускающие движение частиц.' },
    'dust':   { name: 'Пыль', icon: '🌪️', tier: 2, desc: 'Дисперсная фаза твердых микрочастиц в воздухе.' },
    'plant':  { name: 'Растение', icon: '🌱', tier: 2, desc: 'Биологический организм, преобразующий свет в органику.' },
    'mud':    { name: 'Грязь', icon: '💩', tier: 2, desc: 'Пластичная взвесь почвы и воды.' },
    'rain':   { name: 'Дождь', icon: '🌧️', tier: 2, desc: 'Атмосферные осадки, очищающие экосистемы.' },
    'sea':    { name: 'Море', icon: '🌊', tier: 2, desc: 'Обширный соленый водный резервуар.' },
    'stone':  { name: 'Камень', icon: '🪨', tier: 2, desc: 'Твердый обломок горной породы.' },
    'sand':   { name: 'Песок', icon: '🏖️', tier: 2, desc: 'Осадочная порода из мелких зерен кварца.' },
    'clay':   { name: 'Глина', icon: '🏺', tier: 2, desc: 'Мелкозернистый минерал, идеальный для формовки сосудов.' },
    'cloud':  { name: 'Облако', icon: '⛅', tier: 2, desc: 'Конденсированная влага, парящая в атмосфере.' },
    'smoke':  { name: 'Дым', icon: '💨', tier: 2, desc: 'Взвесь углерода и газов при гонении дерева.' },
    'grass':  { name: 'Трава', icon: '🌿', tier: 2, desc: 'Зеленый травянистый покров планеты.' },

    'ocean':  { name: 'Океан', icon: '🔱', tier: 3, desc: 'Глобальный гидрологический объект планетарного масштаба.' },
    'glass':  { name: 'Стекло', icon: '🍷', tier: 3, desc: 'Аморфный прозрачный материал, рожденный в пламени песка.' },
    'metal':  { name: 'Металл', icon: '⚙️', tier: 3, desc: 'Плотный кристаллический проводник, основа инструментов.' },
    'swamp':  { name: 'Болото', icon: '🐊', tier: 3, desc: 'Застойная экосистема с высокой органической активностью.' },
    'life':   { name: 'Жизнь', icon: '✨', tier: 3, desc: 'Сложный органический процесс самовоспроизведения.' },
    'bacteria': { name: 'Бактерия', icon: '👾', tier: 3, desc: 'Простейшие одноклеточные колонизаторы микромира.' },
    'tree':   { name: 'Дерево', icon: '🪵', tier: 3, desc: 'Многолетний одревесневший растительный организм.' },
    'forest': { name: 'Лес', icon: '🌲', tier: 3, desc: 'Сложный биоценоз с древесной доминантой.' },
    'charcoal': { name: 'Уголь', icon: '⚫', tier: 3, desc: 'Высокоуглеродистое ископаемое топливо.' },
    'storm':  { name: 'Шторм', icon: '⛈️', tier: 3, desc: 'Разрушительное атмосферное явление с разрядами тока.' },
    'obsidian': { name: 'Обсидиан', icon: '💎', tier: 3, desc: 'Вулканическое стекло высокой плотности.' },
    'brick':  { name: 'Кирпич', icon: '🧱', tier: 3, desc: 'Обожженный искусственный строительный блок.' },
    'wall':   { name: 'Стена', icon: '🛡️', tier: 3, desc: 'Фортификационная и разделительная конструкция.' },
    'house':  { name: 'Дом', icon: '🏠', tier: 3, desc: 'Защищенное пространство обитания.' },
    'sun':    { name: 'Солнце', icon: '☀️', tier: 3, desc: 'Центральная звезда, дарующая системе свет и гравитацию.' },
    'moon':   { name: 'Луна', icon: '🌙', tier: 3, desc: 'Естественный спутник, влияющий на приливы.' },
    'sky':    { name: 'Небо', icon: '🌌', tier: 3, desc: 'Пространство атмосферы и космического горизонта.' },
    'star':   { name: 'Звезда', icon: '⭐', tier: 3, desc: 'Раскаленный газовый гигант, видимый сквозь световые годы.' },
    'electricity': { name: 'Электро', icon: '🔌', tier: 3, desc: 'Направленный поток заряженных квантовых частиц.' },
    'flower': { name: 'Цветок', icon: '🌸', tier: 3, desc: 'Репродуктивный орган высших растений.' },
    'garden': { name: 'Сад', icon: '🏡', tier: 3, desc: 'Упорядоченный человеком растительный оазис.' },
    'animal': { name: 'Животное', icon: '🐾', tier: 3, desc: 'Многоклеточный подвижный организм.' },
    'human':  { name: 'Человек', icon: '👤', tier: 3, desc: 'Разумный наблюдатель, способный менять архитектуру Вселенной.' },
    'tools':  { name: 'Оснастка', icon: '⚒️', tier: 3, desc: 'Искусственные приспособления для изменения материи.' },
    'fish':   { name: 'Рыба', icon: '🐟', tier: 3, desc: 'Водный позвоночный организм с жаберным дыханием.' },
    'bird':   { name: 'Птица', icon: '🐦', tier: 3, desc: 'Адаптированный к полету теплокровный вид.' },
    'egg':    { name: 'Яйцо', icon: '🥚', tier: 3, desc: 'Защитная сфера инкубации новой жизни.' },
    'turtle': { name: 'Черепаха', icon: '🐢', tier: 3, desc: 'Рептилия с плотным защитным панцирем.' },
    'lizard': { name: 'Ящерица', icon: '🦎', tier: 3, desc: 'Хладнокровное пресмыкающееся существо.' },
    'beast':  { name: 'Зверь', icon: '🐺', tier: 3, desc: 'Хищный представитель высших млекопитающих.' },
    'blood':  { name: 'Кровь', icon: '🩸', tier: 3, desc: 'Транспортная жидкость, несущая кислород клеткам.' },
    'golem':  { name: 'Голем', icon: '🗿', tier: 3, desc: 'Анимированная глиняная скульптура, лишенная души.' },
    'phoenix': { name: 'Феникс', icon: '🐦‍🔥', tier: 3, desc: 'Мифический крылатый дух вечного перерождения.' },
    'paper':  { name: 'Бумага', icon: '📄', tier: 3, desc: 'Тонкое полотно из растительных волокон.' },
    'book':   { name: 'Книга', icon: '📖', tier: 3, desc: 'Хранилище квантов знаний и цивилизационного опыта.' }
};

const recipes = {
    'water+fire': 'steam',
    'earth+fire': 'lava',
    'air+fire': 'energy',
    'air+earth': 'dust',
    'earth+water': 'plant',
    'water+earth': 'mud',
    'water+air': 'rain',
    'water+water': 'sea',
    'sea+sea': 'ocean',
    'air+air': 'cloud',
    'cloud+water': 'rain',
    'lava+water': 'stone',
    'stone+air': 'sand',
    'fire+sand': 'glass',
    'fire+stone': 'metal',
    'mud+plant': 'swamp',
    'swamp+energy': 'life',
    'life+swamp': 'bacteria',
    'plant+earth': 'tree',
    'tree+tree': 'forest',
    'fire+tree': 'charcoal',
    'fire+plant': 'smoke',
    'air+energy': 'storm',
    'lava+stone': 'obsidian',
    'mud+fire': 'clay',
    'clay+fire': 'brick',
    'brick+brick': 'wall',
    'wall+wall': 'house',
    'sky+fire': 'sun',
    'sun+stone': 'moon',
    'air+cloud': 'sky',
    'time+sky': 'night',
    'sky+night': 'star',
    'energy+metal': 'electricity',
    'plant+water': 'grass',
    'grass+sun': 'flower',
    'flower+flower': 'garden',
    'life+earth': 'animal',
    'life+clay': 'golem',
    'life+beast': 'human',
    'human+metal': 'tools',
    'water+life': 'fish',
    'air+life': 'bird',
    'bird+bird': 'egg',
    'egg+sand': 'turtle',
    'egg+swamp': 'lizard',
    'animal+earth': 'beast',
    'human+beast': 'blood',
    'bird+fire': 'phoenix',
    'tools+tree': 'paper',
    'paper+paper': 'book'
};